.TH "rbbr" "1" 
.SH "NAME" 
rbbr \(em browse Ruby classes and documentation 
.SH "SYNOPSIS" 
.PP 
\fBrbbr\fR [\-\-load-modules=\fImodule\fR,...]  
.SH "DESCRIPTION" 
.PP 
This manual page documents briefly the \fBrbbr\fR 	command. This manual page was written for the Debian GNU/Linux 
distribution because the original program does not have a manual page. 
 
.PP 
Rbbr (RuBy BRowser) is an application to browse Ruby's hierarchy of 
modules and classes and their constants and methods. 
 
.SH "OPTIONS" 
.IP "\fB\-\-help\fP" 10 
Show a help text and exit. 
 
.IP "\fB\-\-load-modules\fP" 10 
Specifies dynamic modules to load. 
 
.SH "SEE ALSO" 
.PP 
\fBri\fP\fB(1)\fP 	 
.SH "AUTHOR" 
.PP 
This manual page was written by Dafydd Harries (daf@muse.19inch.net) for the 
Debian GNU/Linux system (but may be used by others). 
 
.\" created by instant / docbook-to-man, Sun 19 Jul 2009, 10:36 
